site_name: Front End Speeches
site_author: Barbara Schiavinato
site_url: https://barbaraschiavinato.github.io/front-end-speeches/
use_directory_urls: false
not_in_nav: |
  /includes
nav:
  - 'Calendar': index.md
  - 'Q1 2025': 
    - 'Github Copilot': 'Q1-2025/github-copilot.md'
    - 'Real-time data': 'Q1-2025/real-time-data.md'

extra_css:
  - assets/stylesheets/neoteroi-mkdocs.css
  - assets/stylesheets/extra.css
extra_javascript:
  - assets/javascripts/extra.js
plugins:
  - search
  - git-authors:
      show_contribution: true
      sort_authors_by: contribution
      show_email_address: true
      exclude: 
        - include/
        - checklists/
        - tags.html
  - page-to-pdf:
      disableOnServe: false
      exclude: 
        - include/
        - tags.html
markdown_extensions:
  - attr_list
  - neoteroi.timeline
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
theme:
  name: material 
  logo: assets/logo.png
  favicon: assets/favicon.ico
  font:
    text: Noto Sans
  features:
    - navigation.instant
    - navigation.indexes
    - navigation.path
    - toc.follow
    - search.suggest
    - content.code.copy
    - content.code.select
    - content.code.annotate

